# -*- coding: utf-8 -*-
"""denoising

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_a70op02E5ePIMFYK0XYhjjOd_BUlBHv
"""

"""
Image Denoising Pipeline (Classical Methods)
--------------------------------------------
Demonstrates classical denoising methods on a single image:
- Gaussian Blur
- Median Filter
- Non-Local Means (NLM)
Computes PSNR and SSIM metrics and saves results as CSV.
Denoised images are saved in 'results/' folder.
"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.metrics import peak_signal_noise_ratio, structural_similarity
import pandas as pd

# -------------------------
# 1️⃣ Get image path from user
# -------------------------
image_path = input("Enter path to your grayscale image: ")

if not os.path.isfile(image_path):
    raise FileNotFoundError(f"Image not found: {image_path}")

image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
if image is None:
    raise ValueError("Failed to load image. Make sure it's a valid grayscale image.")

# Resize if too large
max_dim = 512
if max(image.shape) > max_dim:
    scale = max_dim / max(image.shape)
    image = cv2.resize(image, (int(image.shape[1]*scale), int(image.shape[0]*scale)))

image = image.astype(np.float32)

# -------------------------
# 2️⃣ Add Gaussian noise
# -------------------------
sigma = 25
noise = np.random.normal(0, sigma, image.shape)
noisy_image = np.clip(image + noise, 0, 255).astype(np.uint8)

# -------------------------
# 3️⃣ Classical Denoising
# -------------------------
gaussian_denoised = cv2.GaussianBlur(noisy_image, (5,5), 1.5)
median_denoised = cv2.medianBlur(noisy_image, 3)
nlm_denoised = cv2.fastNlMeansDenoising(
    noisy_image, None, h=10, templateWindowSize=7, searchWindowSize=21
)

# -------------------------
# 4️⃣ Prepare results folder
# -------------------------
os.makedirs("results", exist_ok=True)
cv2.imwrite("results/noisy.png", noisy_image)
cv2.imwrite("results/gaussian.png", gaussian_denoised)
cv2.imwrite("results/median.png", median_denoised)
cv2.imwrite("results/nlm.png", nlm_denoised)

# -------------------------
# 5️⃣ Display results
# -------------------------
titles = ['Original', 'Noisy', 'Gaussian', 'Median', 'NLM']
images = [image, noisy_image, gaussian_denoised, median_denoised, nlm_denoised]

plt.figure(figsize=(18,6))
for i, img in enumerate(images):
    plt.subplot(2, 3, i+1)
    plt.imshow(img, cmap='gray')
    plt.title(titles[i])
    plt.axis('off')
plt.tight_layout()
plt.show()

# -------------------------
# 6️⃣ Compute PSNR & SSIM
# -------------------------
results = {}
for title, img in zip(titles[1:], images[1:]):  # skip Original
    psnr = peak_signal_noise_ratio(image, img, data_range=255)
    ssim = structural_similarity(image, img, data_range=255)
    results[title] = [psnr, ssim]

# -------------------------
# 7️⃣ Save results as CSV
# -------------------------
df = pd.DataFrame.from_dict(results, orient='index', columns=['PSNR','SSIM'])
csv_filename = "results/denoising_results.csv"
df.to_csv(csv_filename)
print(f"Results saved to {csv_filename}")
print(df)